# Generated by Django 3.2.12 on 2022-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keluhan',
            name='pembahasan',
            field=models.TextField(max_length=5000),
        ),
    ]
