# Generated by Django 3.2.12 on 2022-05-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_alter_keluhan_pembahasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='no_hp',
            field=models.IntegerField(max_length=70),
        ),
    ]
