# Generated by Django 3.2.12 on 2022-05-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_alter_biodata_no_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='no_hp',
            field=models.TextField(max_length=13),
        ),
    ]
