# Generated by Django 3.2.8 on 2022-05-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0011_auto_20220527_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
