# Generated by Django 3.2.12 on 2022-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_upload',
            fields=[
                ('ids', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('pembahasan', models.TextField(blank=True, max_length=5000, null=True)),
                ('my_file', models.FileField(blank=True, null=True, upload_to='keluhan/sebelum')),
                ('my_file2', models.FileField(blank=True, null=True, upload_to='keluhan/sesudah')),
                ('deskripsi', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
