# Generated by Django 3.2.12 on 2022-05-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='file_upload',
            name='status',
            field=models.IntegerField(choices=[(1, 'Diajukan'), (2, 'Diproses'), (2, 'Selesai')], default=1),
        ),
    ]
