# Generated by Django 3.2.8 on 2022-05-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0003_alter_file_upload_pembahasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='judul',
            field=models.IntegerField(blank=True, choices=[(1, 'Permasalahan website'), (2, 'Permasalahan database'), (2, 'Permasalahan lainnya')], null=True),
        ),
    ]
