# Generated by Django 3.2.8 on 2022-05-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0005_auto_20220523_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file_upload',
            name='user',
        ),
    ]
