# Generated by Django 3.2.8 on 2022-05-24 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0006_remove_file_upload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_upload',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='file_upload',
            name='status',
            field=models.IntegerField(choices=[(1, 'Diajukan'), (2, 'Diproses'), (3, 'Selesai')], default=1),
        ),
    ]
