# Generated by Django 3.2.8 on 2022-05-24 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('view_keluhan', '0008_file_upload_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file_upload',
            new_name='FileUpload',
        ),
    ]
