# Generated by Django 3.2.8 on 2022-05-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0009_rename_file_upload_fileupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='author',
        ),
    ]
