# Generated by Django 3.2.8 on 2022-05-30 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0011_fileupload_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='author',
        ),
    ]
