# Generated by Django 3.2.8 on 2022-05-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view_keluhan', '0013_fileupload_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='user',
        ),
    ]
