# Generated by Django 3.2.12 on 2022-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=70)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Guest')], null=True)),
            ],
        ),
    ]
