# Generated by Django 3.2.12 on 2022-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'Admin'), (2, 'Guest')], max_length=5, null=True),
        ),
    ]
