# Generated by Django 3.2.8 on 2022-05-27 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_management_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Management',
            new_name='List_User',
        ),
    ]
