# Generated by Django 3.2.8 on 2022-05-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(max_length=5000)),
                ('pembahasan', models.TextField(max_length=13)),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='post/sebelum')),
            ],
        ),
    ]
