# Generated by Django 3.2.8 on 2022-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0002_problem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.AddField(
            model_name='problem',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='post/sesudah'),
        ),
    ]
