# Generated by Django 3.2.8 on 2022-05-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0004_problem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Diajukan'), (2, 'Diproses'), (2, 'Selesai')], null=True),
        ),
    ]
