# Generated by Django 3.2.8 on 2022-05-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0005_problem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.IntegerField(choices=[(1, 'Diajukan'), (2, 'Diproses'), (2, 'Selesai')], default=1),
        ),
    ]
