# Generated by Django 3.2.8 on 2022-05-20 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keluhan', '0006_alter_problem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='teknisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teknisi', to=settings.AUTH_USER_MODEL),
        ),
    ]
