# Generated by Django 3.2.8 on 2022-05-23 04:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keluhan', '0008_auto_20220520_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='List_keluhan',
        ),
    ]
