# Generated by Django 3.2.8 on 2022-05-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0010_auto_20220523_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_keluhan',
            name='judul',
            field=models.IntegerField(choices=[(1, 'Permasalahan website'), (2, 'Permasalahan database'), (2, 'Permasalahan lainnya')], default=1),
        ),
    ]
