# Generated by Django 3.2.8 on 2022-05-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0012_alter_list_keluhan_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_keluhan',
            name='judul',
            field=models.IntegerField(choices=[(1, 'Permasalahan website'), (2, 'Permasalahan database'), (3, 'Permasalahan lainnya')]),
        ),
        migrations.AlterField(
            model_name='list_keluhan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Diajukan'), (2, 'Diproses'), (3, 'Selesai')], default=1),
        ),
    ]
