# Generated by Django 3.2.8 on 2022-05-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0013_auto_20220524_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_keluhan',
            name='pembahasan',
            field=models.CharField(max_length=5000),
        ),
    ]
