# Generated by Django 3.2.8 on 2022-05-30 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('keluhan', '0014_alter_list_keluhan_pembahasan'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_keluhan',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
